yestephan/savecue

- app/controllers/pages_controller.rb
- config/routes.rb
Route, controller and view are updated for the css components.
> route is updated

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_login.scss
- app/assets/stylesheets/pages/_signup.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> added sigin and login style

- app/models/account.rb
- app/models/user.rb
- app/models/user_cue.rb
- db/migrate/20220302122301_remove_bank_account_from_users.rb
- db/migrate/20220302122400_create_accounts.rb
- db/migrate/20220302123416_add_creditor_account_to_user_cues.rb
- db/migrate/20220302123544_add_debtor_account_to_user_cues.rb
- db/migrate/20220302155054_add_fields_to_accounts.rb
- db/schema.rb
- db/seeds.rb
- test/models/account_test.rb
added model for bank account and connected it to user and user_cues + updated the seed
> Bank Account Model

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_cues.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/cues_controller.rb
- app/controllers/user_cues_controller.rb
- app/views/cues/index.html.erb
- config/routes.rb
- db/seeds.rb
> add cue card in cue#index

- app/assets/stylesheets/pages/_cues.scss
- app/controllers/user_cues_controller.rb
- app/views/cues/index.html.erb
- app/views/user_cues/new.html.erb
just add link between bank account setup and cues 
and add card cue style
> link between setup

- Gemfile
- Gemfile.lock
- app/controllers/profiles_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/profiles/edit.html.erb
- app/views/shared/_avatar.html.erb
- app/views/shared/_navbar.html.erb
- config/initializers/cloudinary.rb
- db/migrate/20220303174736_remove_full_name_from_user.rb
- db/migrate/20220303174753_add_first_name_and_last_name_to_user.rb
- db/migrate/20220303180252_add_picture_to_users.rb
- db/schema.rb
- db/seeds.rb
I created edit profile apart from user account because I tried everything I could to make it work together with devise but at the end I couldn't. So this way devise alone manages email and password and profile does the name and upload photo. Please don't forget to run `bundle install` and setup your `.env` file after updating your local.
> Edit profile

- app/controllers/cues_controller.rb
- app/views/cues/index.html.erb
- app/views/user_cues/new.html.erb
> solved the arrow back

- app/controllers/cues_controller.rb
- app/views/accounts/form.html.erb
- app/views/cues/index.html.erb
- app/views/user_cues/new.html.erb
add button background style and edit the information
> edit information and edit button color

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/profiles/home.html.erb
> add button style

- app/controllers/cues_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/user_cues_controller.rb
- app/views/user_cues/new.html.erb
> Setup cues info

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_util.scss
- app/assets/stylesheets/config/_colors.scss
- app/controllers/cues_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/user_cues_controller.rb
- app/javascript/controllers/toggle_controller.js
- app/views/cues/index.html.erb
- app/views/pages/ui_kit.html.erb
- app/views/profiles/home.html.erb
- config/routes.rb
Fixed the add more cues button
> Add more cues

- app/controllers/accounts_controller.rb
changed to path to change accounts since the routes were changed now it requires account/:id to update it
> Fixed error on edit account

- app/controllers/cues_controller.rb
- app/views/cues/index.html.erb
- db/seeds.rb
solved the bug for the filter of the cue
> Filter usercues

- app/controllers/accounts_controller.rb
- app/controllers/profiles_controller.rb
- app/controllers/user_cues_controller.rb
- app/models/account.rb
- app/models/user.rb
- app/views/accounts/form.html.erb
- app/views/user_cues/new.html.erb
- config/routes.rb
- db/seeds.rb
changed the confirmation button for the new cue + made account type enforced and simplified the access to the user accounts
> confirmation button/user accounts types

- app/controllers/profiles_controller.rb
Just updated the big spender background.
> Big spenda background is nor updated

- db/seeds.rb
- lib/tasks/test_namespace.rake
- lib/tasks/transactions.rake
> Trigger part 2

- app/assets/stylesheets/pages/_home.scss
- app/views/profiles/home.html.erb
> Show setup amount homepage

- app/assets/stylesheets/pages/_confirmation.scss
- app/controllers/accounts_controller.rb
- app/controllers/pages_controller.rb
- app/views/pages/confirm.html.erb
- config/routes.rb
The confirmation screen is ready now. Please review.
> Confirmation screen

- app/assets/stylesheets/pages/_confirmation.scss
- app/controllers/accounts_controller.rb
- app/controllers/pages_controller.rb
- app/helpers/application_helper.rb
- app/models/user.rb
- app/views/accounts/form.html.erb
- app/views/pages/confirm.html.erb
- config/routes.rb
The back button is not looping anymore:) Please review!
> Back button loop

- app/helpers/application_helper.rb
solved the bug for "big spenda"
> solved question

- db/seeds.rb
> fixed the seed file a bit and added a favicon

- app/controllers/profiles_controller.rb
- app/helpers/application_helper.rb
- app/models/user.rb
- app/views/profiles/home.html.erb
- db/seeds.rb
- lib/tasks/transactions.rake
> Trigger money

- app/views/shared/_navbar.html.erb
I've just realised this branch is not merged yet. This is the onboarding. Please review.
> The onboarding is corrected

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/profiles_controller.rb
- app/views/profiles/home.html.erb
- db/seeds.rb
- yarn.lock
Fixed the sizing and details card
> fixed things

- .gitignore
- app/controllers/pages_controller.rb
- app/controllers/user_cues_controller.rb
- app/views/cues/index.html.erb
- app/views/pages/home.html.erb
- app/views/profiles/home.html.erb
- app/views/user_cues/edit.html.erb
- app/views/user_cues/new.html.erb
This branch is related to onboarding. Please review.
> Onboarding is now here

- app/helpers/application_helper.rb
> The edit cue button is now working

- app/views/layouts/application.html.erb
Tiny fix, updated our title to include our tagline
> added the title tag

- app/assets/stylesheets/config/_colors.scss
- app/helpers/application_helper.rb
- db/seeds.rb
I've changed the background for big spenda to purple. It was sooooo red. 
Please review.
> Background color for big spenda

- app/helpers/application_helper.rb
> fixed the edit accounts bug

- app/helpers/application_helper.rb
- db/seeds.rb
- lib/tasks/transactions.rake
> wine cue added and working with all transactions
